In [2]:
import torch
import numpy as np

In [40]:
# Check if Apple Silicon GPU acceleration is available
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using Apple Silicon GPU (MPS)")
else:
    device = torch.device("cpu")
    print("MPS not available, falling back to CPU")

Using Apple Silicon GPU (MPS)


In [ ]:
## Initializing a tensor from a data

data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [5]:
## Initializing a tensor from a numpy array

np_array = np.array([[1,2],[3,4]])
x_np = torch.tensor(np_array)

In [6]:
## Retaining the properties/shape of a tensor
x_ones = torch.ones_like(x_data)
print(f"x_ones:{x_ones}")

x_ones:tensor([[1, 1],
        [1, 1]])


In [7]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"x_rand:{x_rand}")

x_rand:tensor([[0.9511, 0.7268],
        [0.4782, 0.9675]])


In [9]:
tensor = torch.rand(3,5)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 5])
torch.float32
cpu


In [21]:
a = torch.rand((3,4),dtype=torch.float)
print(f"a: {a}")

a: tensor([[0.5383, 0.4581, 0.6447, 0.4031],
        [0.1012, 0.7620, 0.2432, 0.5521],
        [0.3461, 0.9977, 0.5185, 0.3869]])


In [22]:
b = torch.rand((3,4),dtype=torch.float)
print(f"b: {b}")

b: tensor([[0.6351, 0.1294, 0.8207, 0.3193],
        [0.1367, 0.7152, 0.4871, 0.6498],
        [0.2928, 0.5865, 0.1167, 0.0207]])


In [23]:
print(a*b)

tensor([[0.3419, 0.0593, 0.5291, 0.1287],
        [0.0138, 0.5450, 0.1185, 0.3587],
        [0.1013, 0.5852, 0.0605, 0.0080]])


In [25]:
print(a@b.T)

tensor([[1.0591, 0.9773, 0.5099],
        [0.5388, 1.0361, 0.5164],
        [0.8980, 1.2649, 0.7550]])


In [26]:
print(b.T)

tensor([[0.6351, 0.1367, 0.2928],
        [0.1294, 0.7152, 0.5865],
        [0.8207, 0.4871, 0.1167],
        [0.3193, 0.6498, 0.0207]])


In [27]:
a

tensor([[0.5383, 0.4581, 0.6447, 0.4031],
        [0.1012, 0.7620, 0.2432, 0.5521],
        [0.3461, 0.9977, 0.5185, 0.3869]])

In [28]:
a[0]

tensor([0.5383, 0.4581, 0.6447, 0.4031])

In [33]:
a[:,-1]

tensor([0.4031, 0.5521, 0.3869])

In [37]:
torch.cat([a,b],dim=0)

tensor([[0.5383, 0.4581, 0.6447, 0.4031],
        [0.1012, 0.7620, 0.2432, 0.5521],
        [0.3461, 0.9977, 0.5185, 0.3869],
        [0.6351, 0.1294, 0.8207, 0.3193],
        [0.1367, 0.7152, 0.4871, 0.6498],
        [0.2928, 0.5865, 0.1167, 0.0207]])

In [38]:
a.sum()

tensor(5.9521)

In [51]:
a = torch.randn((2000,2000))
b = torch.randn((2000,2000))

In [52]:
a = a.to(device=device)
b= b.to(device)